version: "3"

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

volumes:
  smtp_maildir:

services:
  georchestra.mydomain.org:
    image: traefik:1.7
    ports:
      - "80:80"
      - "443:443"
      # uncomment the next line to get a web ui + api at https://georchestra.mydomain.org:8080/traefik/
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/ssl:/etc/traefik/ssl/
      - ./resources/traefik.toml:/traefik.toml
    restart: always


  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"

  cas:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cas"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/cas"

  smtp:
    image: camptocamp/smtp-sink:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    restart: always

  courier-imap:
    image: camptocamp/courier-imap:latest
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    restart: always

  webmail:
    image: camptocamp/sqwebmail:latest
    environment:
      - IMAP_HOSTNAME=courier-imap
      - SMTP_HOSTNAME=smtp-sink
    volumes:
      - smtp_maildir:/home/smtp/Maildir/
    labels:
      - "traefik.enable=true"
      - "traefik.backend=webmail"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/webmail"
    restart: always

  ssh:
    image: georchestra/ssh_data:latest
    ports:
      - "2222:22"
    volumes:
      - geoserver_geodata:/mnt/geoserver_geodata
    restart: always
