version: '2'

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

services:
  georchestra.mydomain.org:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      # uncomment the next line to get a web ui + api at https://georchestra.mydomain.org:8080/traefik/
      #- "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/ssl:/etc/traefik/ssl/
      - ./resources/traefik.toml:/traefik.toml

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"

  smtp:
    image: camptocamp/smtp-sink:latest

  courier-imap:
    image: camptocamp/courier-imap:latest
    volumes_from:
      - smtp:rw

  webmail:
    image: camptocamp/sqwebmail:latest
    ports:
      - "8081:80"
    volumes_from:
      - smtp:rw

  ssh:
    image: georchestra/ssh_data:latest
    ports:
      - "2222:22"
    volumes:
      - geoserver_geodata:/mnt/geoserver_geodata
