version: "3"

volumes:
  geowebcache_tiles:
  geowebcache_datadir:

services:

  # standalone geowebcache:
  geowebcache:
    image: georchestra/geowebcache:19.04
    volumes:
      - geowebcache_datadir:/mnt/geowebcache_datadir
      - geowebcache_tiles:/mnt/geowebcache_tiles
      - ./config:/etc/georchestra
    environment:
      - XMS=1G
      - XMX=2G

  # atlas printing services, eventually queried by the mapfishapp atlas addon
  atlas:
    image: georchestra/atlas:19.04
    volumes:
      - ./config:/etc/georchestra
    environment:
      - XMS=512M
      - XMX=2G
